### ISSUE TITLE
How to Setup  Tecton in my local for testing.

### ISSUE THREAD

**Issue by NaveenVinayakS** [tecton-ai-ext/tecton-terraform-setup#39]
Hi, 

I am trying to setup tecton in my local for testing. i have used **pip install tecton** but when i give **tecton login** no respose in my CLI.
can someone guid me  how to setup tecton step by step.?

**Comment by jackwellsxyz** [comment]
Hi @NaveenVinayakS thanks for your comment. You'll need an active Tecton account to leverage this repository - if you don't have one, reach out to us via the "Request a free trial" button on our [web site](https://tecton.ai). Alternatively, you might also want to check out [Feast](https://feast.dev), an open source feature store that dovetails nicely with Tecton. You can also join in the conversation via our [Slack workspace](https://slack.feast.dev). Hope this helps!
